artifact_location: //home/elicoubuntu/Producto_de_Datos/Demos/Mlflow-demo-3/workspace/mlflow/corridas/678094588728581938
creation_time: 1710466593109
experiment_id: '678094588728581938'
last_update_time: 1710466593109
lifecycle_stage: active
name: red-wine
