digest: 466e6837
name: dataset
profile: '{"num_rows": 1199, "num_elements": 13189}'
schema: '{"mlflow_colspec": [{"type": "double", "name": "fixed acidity", "required":
  true}, {"type": "double", "name": "volatile acidity", "required": true}, {"type":
  "double", "name": "citric acid", "required": true}, {"type": "double", "name": "residual
  sugar", "required": true}, {"type": "double", "name": "chlorides", "required": true},
  {"type": "double", "name": "free sulfur dioxide", "required": true}, {"type": "double",
  "name": "total sulfur dioxide", "required": true}, {"type": "double", "name": "density",
  "required": true}, {"type": "double", "name": "pH", "required": true}, {"type":
  "double", "name": "sulphates", "required": true}, {"type": "double", "name": "alcohol",
  "required": true}]}'
source: '{"tags": {"mlflow.user": "elicoubuntu", "mlflow.source.name": "demo1.py",
  "mlflow.source.type": "LOCAL", "mlflow.source.git.commit": "687524a82b9fd46600da4c92a362080c94567c78"}}'
source_type: code
